---
title: "Statistical Data Science"
author: "PSTAT 134/234"
date: "Fall 2024"
output: pdf_document
header-includes:
    - \usepackage{geometry}
    - \usepackage{fancyhdr}
    - \usepackage{url}
    - \usepackage{booktabs}
    - \usepackage{hyperref}
    - \usepackage{color}
    - \usepackage{lastpage}
    - \usepackage{multirow}
    - \usepackage{graphicx}
    - \usepackage{lscape}
    - \usepackage{float}
#    - \usepackage{draftwatermark}
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- \documentclass[11pt]{article} -->
<!-- \usepackage[left=1in,top=1in,right=1in,bottom=1in,headheight=14pt]{geometry} -->
<!-- \usepackage{fancyhdr} -->
<!-- \usepackage{url} -->
<!-- \usepackage{booktabs} -->
<!-- \usepackage{hyperref} -->
<!-- \usepackage{color} -->
<!-- \usepackage{lastpage} -->
<!-- \usepackage{multirow} -->
<!-- \usepackage{graphicx} -->
<!-- \usepackage{lscape} -->
<!-- \hypersetup{colorlinks=true, urlcolor=blue} -->

<!-- \title{Introduction to Statistical Machine Learning} -->
<!-- \author{PSTAT 131/231} -->
<!-- \date{Winter 2022} -->

\pagestyle{fancy}
\lhead{Fall 2024}
\chead{}
\rhead{134/234 Syllabus}
\lfoot{}
\cfoot{\small \thepage}
\rfoot{}

<!-- \begin{document} -->
<!-- \maketitle -->
\begin{center}
\begin{tabular}{ll}
\textsc{Instructor:} &Dr. Katie Coburn (\href{mailto:katie\_m\_coburn@ucsb.edu}{\texttt{katie\_m\_coburn@ucsb.edu}}) \\
\textsc{Teaching Assistants:} &Mengye Liu (\href{mailto:mengye@ucsb.edu}{\texttt{mengye@ucsb.edu}})\\
    &Lihao Xiao (\href{mailto:lihao@ucsb.edu}{\texttt{lihao@ucsb.edu}}) \\
\textsc{Lectures:} &TR 3:30 - 4:45 pm CHEM 1171 \\
\textsc{Sections:}
&W 10:00 - 10:50 am PHELP 1525 \textsc{Liu} \\
&W 11:00 - 11:50 am PHELP 1525 \textsc{Liu} \\
&W 12:00 - 12:50 pm PHELP 1525 \textsc{Xiao} \\
&W 1:00 - 1:50 pm PHELP 1525 \textsc{Xiao} \\
\end{tabular}
\end{center}

\section*{Course information}

\subsection*{Description}
\textsc{Applications} of advanced data science tools for data retrieval, statistical analysis and machine learning, optimization, and visualization. Multiple case studies will illustrate the practical use of these tools. Prerequisites: PSTAT 131 or 231 or CS 165B and CS 9 (preferred) or CS 16, all with a minimum grade of C or better. Credit units: 4.

\vskip6pt\noindent \textsc{This course} is taught at two levels, one aimed at undergraduates (134 level) and one at graduate students (234 level). Lectures are given at a level intended to be accessible and relevant to all students in the course. Students taking the course at the 234 level will be assigned \textbf{additional homework questions}. The final project assignment is the same for both levels.

\subsection*{Attendance}
\textsc{Lectures} and lab sections will be conducted in person only. We will not record lectures or labs. You are strongly encouraged to attend \textbf{all} lectures and lab sections; choosing not to attend will result in your missing the (potentially very important) content that was presented or discussed.

\vskip6pt\noindent If you choose not to attend a lecture or section, you are still expected to complete the assignments and readings. If you are unable to attend for any \textbf{university-sanctioned reason}, please inform the instructor and your TA(s) as soon as possible.

\subsection*{Format}
\textsc{Lectures} and sections will be provided \textbf{in person only}. You are expected to attend every lecture and section. Lecture slides will be posted on Canvas before the corresponding class. The class will progress according to a weekly schedule (provided below). Both lecture periods each week will consist of slides that cover related concepts, sometimes including live coding to demonstrate how to apply the concepts. 

\vskip6pt\noindent Section each week will be dedicated to completing an R- and Python-based lab. Section attendance is recorded and is \textbf{very strongly} recommended, since doing so will enable you to learn and practice your coding skills in an environment where you can easily obtain help from the TA(s) and your peers.

\vskip6pt\noindent Should you need to switch sections, please ask the TA of the section you want to switch to if there is room for you to attend. If the TA allows, you can then begin attending the new section while remaining officially enrolled in your previous section. \textbf{Sections will be held beginning the week of September 30th}.

<!-- \newpage -->
\subsection*{Required Materials}
\textsc{The required materials} used for this class are as follows. Note that all are freely available online and do not require purchase.

\begin{itemize}
    \item \textbf{Required Books:}
    \begin{itemize}
      \item \textit{R for Data Science} Second Edition, by H. Wickham, M. Cetinkaya-Rundel, G. Grolemund. Available: \href{https://r4ds.hadley.nz/}{https://r4ds.hadley.nz/}
      \item \textit{Python Data Science Handbook}, by J. VanderPlas. \href{https://jakevdp.github.io/PythonDataScienceHandbook/}{Available here}
    \end{itemize}
    \item \textbf{Required Software:}
    \begin{itemize}
      \item The R statistical environment version 4.4.1, available here: \href{https://www.r-project.org/}{https://www.r-project.org/}
      \item The RStudio IDE (integrated development environment) Desktop version. Available: \href{https://www.rstudio.com/products/rstudio/download/#download}{https://www.rstudio.com/} 
      \item The Python programming language version 3.12 or higher, available here: \href{https://www.python.org/downloads/}{https://www.python.org/downloads/}
    \end{itemize}
\end{itemize}

\subsection*{Supplemental Materials}
\textsc{The following} are materials that are \textbf{not required} for this course, but are \textbf{recommended}. Do not feel expected to read all of these; instead I encourage you to use them as reference manuals and look subjects up as necessary. You will not be quizzed on any readings from these books unless directly specified.

\begin{itemize}
    \item \textit{Python for Data Analysis} Third Edition, by W. McKinney. Available: \href{https://wesmckinney.com/book/}{https://wesmckinney.com/book/}
    \item \textit{The StatQuest Illustrated Guide to Machine Learning}, by J. Starmer. Available \href{https://www.amazon.com/dp/B0BLM4TLPY}{on Amazon}: \$27 for paperback. Based on videos available free at \href{https://www.youtube.com/@statquest}{https://www.youtube.com/@statquest}
    \item \textit{Supervised Machine Learning for Text Analysis in R}, by E. Hvitfeldt and J. Silge. Available: \href{https://smltar.com/}{https://smltar.com/}
    \item \textit{Feature Engineering and Selection}, by M. Kuhn and K. Johnson. Available: \href{http://www.feat.engineering/}{http://www.feat.engineering/}
    \item \textit{R Markdown Cookbook}, by Y. Xie, C. Dervieux and E. Riederer. Available: \href{https://bookdown.org/yihui/rmarkdown-cookbook/}{https://bookdown.org/yihui/rmarkdown-cookbook/}
    \item \textit{Tidy Modeling with R}, by M. Kuhn and J. Silge. Available: \href{https://www.tmwr.org/}{https://www.tmwr.org/}
    \item \textit{Text Mining with R: A Tidy Approach}, by J. Silge and D. Robinson. Available: \href{https://www.tidytextmining.com/}{https://www.tidytextmining.com/}
    \item \textit{Natural Language Processing with Python}, by S. Bird, E. Klein, and E. Loper. Available: \href{https://www.nltk.org/book/}{https://www.nltk.org/book/}
\end{itemize}

\subsection*{Learning Outcomes}
Upon completion of this course, students should be able to:
\begin{enumerate}
    \item \textsc{Demonstrate} the ability to use appropriate statistical methodologies for real-world data analysis settings;
    \item \textsc{Apply} a variety of technological tools, such as statistical software and computer programming languages, for the purpose of statistical data analysis;
    \item \textsc{Communicate} data science concepts and reasoning in written reports and oral presentations using both technical and non-technical language;
    \item \textsc{Participate} effectively in teams to accomplish the goals of a data science project.
\end{enumerate}

<!-- \newpage -->
\subsection*{Assessments}
\textsc{Your attainment} of these course learning outcomes will be measured by the following assessments, with the relative weighting indicated in parentheses. All assignments within each category are given equal weight.

\vskip6pt\noindent Collaboration and open science are fundamental aspects of data science. You can (and in fact are encouraged) to use the Internet, StackOverflow, etc. as a resource when coding. However, you \textbf{should not} directly copy code or answers. Your code should be well documented; include comments describing each line. If you use a source for help coding, you \textbf{must} cite it. You \textbf{are permitted} to collaborate/work in groups on the homework if you choose; if you choose to do so, you should list the names of the students you worked with at the beginning of your submitted homework assignment.

\vskip6pt\noindent You are permitted to make use of multimodal large language models (like ChatGPT) when writing the \textbf{code} portions of assignments if you choose. However, you should be aware that the work of such models is often flawed at best, if not outright inaccurate, and be prepared to double- and triple-check your work before submission. If you do use ChatGPT for \textbf{any} part of your code, you absolutely \textbf{must cite} the use of ChatGPT, specifically indicating exactly which lines it was used for and what prompt(s) it was given. If we detect your use of ChatGPT \textbf{without} such a citation, it will be considered plagiarism and handled accordingly. You are \textbf{not permitted} to use ChatGPT to write the text portions of assignments; if we detect such use, it will also be considered plagiarism.

\begin{itemize}
\item \textbf{Homework} (30\%). Homework is assigned approximately every two weeks (this may vary) and will always be due by Sundays at 11:59 PM PDT. It will be \textbf{graded for accuracy} and solutions for the homework assignments will be posted approximately one week after each deadline. The graduate students will need to complete additional questions, but all assignments are ultimately rescaled to be out of 50 points. There are a total of \textbf{five} homework assignments and none will be dropped. 

\item \textbf{Labs} (20\%). Section attendance is mandatory, and will be measured through the completion of a lab. Upon participating and completing the labs, you will receive credit for section attendance. You may miss a total of \textbf{two} sections without penalty. Doing the labs will be greatly beneficial for your homework, quiz, and project grades; with that in mind, you are strongly encouraged to attend all lab sections and follow along with the materials for each lab.

\item \textbf{Quizzes} (20\%) Each week, beginning the week of \textbf{October 7th} and continuing through week 9, there will be a short quiz posted on Canvas. Note that there will be no quiz during Thanksgiving week. There will be a total of \textbf{six quizzes}, with \textbf{no make-up} quizzes. Your lowest quiz score will be dropped.

You will have a 24-hour window to take each quiz; that window will begin at 8:00 AM Thursday and close at 8:00 AM Friday. Within that window, each quiz will have a 15-minute time limit, which will begin once you open the assignment. (DSP accommodations will be built in via Canvas; make sure you submit an instructor letter for any necessary accommodations.) The quizzes will consist of a few questions similar to the homework; they may be conceptual questions, they may ask you to interpret some results, or they may ask you to perform some analyses. They are meant to serve as academic markers to provide an ongoing assessment of your understanding and to flag areas that may require more attention.

If you do not remember to log in and complete the quiz during that designated 24-hour window, you will receive a zero for that quiz, with no exceptions.

\item \textbf{Final Project} (30\%). The final project is an important portion of the class and allows students to demonstrate their understanding of the material by working with a data set of their choice. Students should begin thinking about a project, forming groups of four (4), and looking for a data set immediately; a page on Canvas provides a list of possible resources. You will receive a considerable amount of guidance about the project over the course of the quarter.

\vskip6pt\noindent During the final exam time for the course (\textbf{Thursday, December 12th from 4:00 to 7:00 PM}), all groups will be required to give a short five-minute presentation on their project, in the form of either a poster or PowerPoint-style slideshow, followed by answering three minutes of questions. Your group will also need to submit a short (3-5 paragraph) report on your project, in the form of a Markdown or Quarto file or a Jupyter notebook.

\vskip6pt\noindent The project will require work and cannot be satisfactorily completed in only a day (or even a week). You are \textbf{strongly advised} to work on it in stages throughout the quarter. See Canvas for more detailed instructions and a rubric. 

\end{itemize}

\subsection*{Tentative Course Schedule}
\textsc{The weekly} schedule is indicated below. The topics and reading are subject to change based on the progress of the class.

\begin{table}[H]
\begin{tabular}{@{}llll@{}}
\toprule
                & \textbf{Topic}        & \textbf{Assignment}                                            & \textbf{Project Stage} \\ \midrule
\textbf{Week 1} & Intro to data science           & Data Memo                                                               & Pick topic             \\
\textbf{Week 2} & Application programming interfaces (APIs)     & Homework 1 & Find data              \\
\textbf{Week 3} & Web scraping   &                                                     & Tidy data              \\
\textbf{Week 4} & Data visualization & Homework 2                                                     & EDA                    \\
\textbf{Week 5} & Data cleaning \& feature engineering &                                                   &                     \\
\textbf{Week 6} & Data manipulation       & Homework 3                                                     & Run models             \\
\textbf{Week 7} & Natural language processing (NLP)    & Homework 4                                                     &                        \\
\textbf{Week 8} & Recommender systems            &                                                      & Write-up               \\
\textbf{Week 9} & Image classification                  & Homework 5                                                              & Edits                  \\
\textbf{Week 10} & Effective communication       & Final Project                                                  & Final draft            \\ \bottomrule
\end{tabular}
\end{table}

\subsection*{Time Commitment}
\textsc{The course} is 4 credit units; each credit unit corresponds to an approximate time commitment of 3 hours. You should expect to allocate 12 hours per week to the course. If you find yourself spending considerably more time on the course on a regular basis, please let the instructor or TAs know so that we can help you balance the workload.

\noindent A suggested allocation of this time is as follows: 
\begin{itemize}
    \item Reading and class time: 3 hours (25\%)
    \item Homework: 4.5 hours (37.5\%)
    \item Sections: 1 hour (8.3\%)
    \item Final project: 4.5 hours (37.5\%)
\end{itemize}

<!-- %\newpage -->
\section*{Course Policies}

\subsection*{Communication}
\textsc{There are four} means of communication with other students or the instructional team: during/after class, office hours, email, and individual appointments. \textbf{Please use them in that order}. Note that I can be slow at responding to email, which is why it is low on the list; to compensate, however, I offer several office hours weekly and am always willing to discuss problems or answer questions in person/during class.
\begin{enumerate}

    \item \textbf{During/after class}. The easiest guaranteed way to contact me is to come up after class and say hello, or to raise your hand and ask a question during class.
    
    \item \textbf{Office hours}. Office hours are offered at a minimum of twice weekly. I hold one session of 4 hours a week, and the other(s) are held by various combinations of TAs or ULAs. These are opportunities to interact informally, ask questions, and discuss course material or assignments.
    
    \item \textbf{Email}. Please use email with discernment for simple communication. A response is guaranteed within 48 weekday hours (so if you email on Friday afternoon, you may not receive a reply until Tuesday afternoon). If your message is time-sensitive, please indicate so in the subject, and I will do my best to respond promptly.

    \item \textbf{Appointment}. You can schedule individual 20-minute appointments with me as needed. These appointments may be either on Zoom or in person. This mode of communication is best suited to more complex or nuanced communication regarding personal matters. If you schedule an appointment, you will be prompted to indicate what you wish to discuss. 
\end{enumerate}

\subsection*{Extra Credit} 
\textsc{If the class} reaches a 90\% submission rate of course evaluations at the end of the quarter, the \textbf{entire class} will receive 5 free points on the final project.

<!-- %\newpage -->
\subsection*{Grades} 
\textsc{Your overall grade} in the course will be calculated as the weighted average of the proportions of total possible points in each assessment category according to the weightings indicated in the Assessments section and reported as a percentage rounded to two decimal places. Letter grades will be assigned according to the rubric below.

\begin{center}
\begin{tabular}{lr}
    A+ &100\% \\
    A &94\% -- 99.99\%  \\
    A- &90\% -- 93.99\% \\
    B+ &87\% -- 89.99\% \\
    B &84\% -- 86.99\% \\
    B- &80\% -- 83.99\% \\
    C+ &77\% -- 79.99\% \\
    C &74\% -- 76.99\% \\
    C- &70\% -- 73.99\% \\
    D+ &67\% -- 69.99\% \\
    D &64\% -- 66.99\% \\
    D- &60\% -- 63.99\% \\
    F &0\% -- 59.99\%
\end{tabular}
\end{center}

\noindent \textsc{You can} keep track of your marks on individual assessments, your marks in each assessment category, and your overall grade in the Canvas gradebook. Please notify the instructor or TAs of any errors in grade \textit{entry}; please do not attempt to negotiate the grades themselves. If at the end of the course you believe your grade was unfairly assigned, you are entitled to contest it according to the procedure outlined \href{https://my.sa.ucsb.edu/catalog/Current/AcademicPoliciesProcedures/ContestedGrades.aspx}{here} in the UCSB General Catalog.

\subsection*{Deadlines} 
\textsc{You receive} two free late homework submissions without penalty. This policy applies only to homeworks. When you wish to use one of these late submissions, simply submit within one week of the original deadline, and \textbf{add a note} at the beginning of the assignment explaining that it is a free late submission.

\vskip6pt\noindent \textsc{Non-exempted} homeworks submitted within one week of the deadline will be awarded 50\% credit. \textbf{No credit} will be awarded for homework turned in more than one week late; please plan ahead and submit your work on time. No late quizzes will be accepted.

\vskip6pt\noindent \textsc{The final project} deadline is firm and no late submissions will be accepted.

\subsection*{Extensions} 
\textsc{Extensions} may be granted based on individual circumstances at the instructor's discretion.

\subsection*{Conduct} 
\textsc{Please be mindful} of maintaining respectful and kind communication.  You are expected to uphold the UCSB student code of conduct in your behavior when in class, in section, or interacting with other students or the instructional team. You can find the student code of conduct on the Office of Student Conduct website from \href{http://studentconduct.sa.ucsb.edu/policies-procedures}{this page}. If you are uncomfortable with the conduct of another individual for any reason, please notify the instructor or TAs.

\subsection*{Academic Integrity} 
\textsc{Please maintain integrity} in learning. Your work in the course must be your own. Any form of plagiarism, cheating, misrepresentation of individual effort on assignments and assessments, falsification of information or documents, or misuse of course materials compromises your own learning experience, that of your peers, and undermines the integrity of the UCSB community. Any evidence of dishonest conduct will be discussed with the student(s) involved and reported to the Office of Student Conduct. Depending on the nature of the evidence and the violation, penalty in the course may range from loss of credit to automatic failure. For a definition and examples of dishonesty, a discussion of what constitutes an appropriate response from faculty, and an explanation of the reporting and investigation process, see the \href{https://studentconduct.sa.ucsb.edu/academic-integrity}{OSC page on academic integrity}. 

\subsection*{Accommodations} 
\textsc{Reasonable accommodations} will be made for any student with a qualifying disability. Such requests should be made through the Disabled Students Program (DSP). More information, instructions on how to access accommodations, and information on related resources can be found on \href{https://dsp.sa.ucsb.edu/}{DSP website}. Remote learning may present unique accommodation needs requiring additional flexibility; students receiving accommodation via DSP are invited to discuss this with the instructor if desired.

\subsection*{Student Evaluations} 
\textsc{Toward the end} of the term, you will be given an opportunity to provide feedback about the course. Your suggestions and assessments are essential to improving the course, so please take the time to fill out the evaluations thoughtfully. 

\subsection*{Student Resources}
\textsc{Any students} in need are encouraged to make use of the following resources.

\begin{itemize}
    \item Financial Crisis Response Team \\ 
    \href{https://food.ucsb.edu/about/committees/financial-crisis-response-team}{https://food.ucsb.edu/about/committees/financial-crisis-response-team}
    \item Food Security and Basic Needs (Food, Housing, Technology) Advising Center \\
    \href{https://food.ucsb.edu/resources/basic-needs-advocates}{https://food.ucsb.edu/resources/basic-needs-advocates}
    \item Undocumented Student Services \\
    \href{http://www.sa.ucsb.edu/dreamscholars/home}{http://www.sa.ucsb.edu/dreamscholars/home}
    \item Campus Advocacy, Resources, and Education (CARE) \\
    \href{https://care.ucsb.edu/}{https://care.ucsb.edu/} \\
    24/7 Confidential Phone: (805) 893-4613
    \item The Trevor Project \\  \href{https://www.thetrevorproject.org/}{https://www.thetrevorproject.org/}
    \item Counseling and Psychological Services (CAPS) \\ 
    \href{https://caps.sa.ucsb.edu/}{https://caps.sa.ucsb.edu/} \\
    24/7 Counselors: (805) 893-4411, press 2
\end{itemize}
