---
title: "Introduction and Syllabus"
author: "PSTAT 134/234"
format:
  revealjs:
    slide-number: c
    theme: night
editor: source
---

## Introduction

::: columns
::: {.column width="40%"}
About This Course
:::

::: {.column width="60%"}
Right column
:::
:::

```{python, echo=TRUE}
import numpy as np
import matplotlib

def say_hello(name):
    print('Hello {name}'.format(name=name))
    
say_hello("Tony")
```

::: notes
Test of the speaker notes
:::

## Bullets

When you click the **Render** button a document will be generated that includes:

-   Content authored with markdown
-   Output from executable code

## Labs

-   Week 1: Basic Setup, intro to Python and RStudio, intro to Quarto/using Python and R interchangeably; basics of R and Python

-   Week 2: Introduction to APIs

-   Week 3: When the API Doesn't Exist: Intro to Web Scraping

-   Week 4: Data Cleaning

-   Week 5: Data Manipulation

-   Week 6: Effective Data Visualization

-   Week 7: Case Study 1: Natural Language Processing

-   Week 8: Case Study 2: Recommender Systems

-   Week 9: Case Study 3: Image Classification

-   Week 10: 

## Syllabus

Course definition: Applications of advanced data science tools for data retrieval, statistical analysis and machine learning, optimization, and visualization. Multiple case studies will illustrate the practical use of these tools.

Basics of R and Python for Data Analysis - How to set up a Quarto or Markdown file - Setting up installations of R, RStudio, and Anaconda

Data retrieval - Practice accessing data from an API - Practice creating a basic web scraper - Cleaning data

Data visualization/exploratory data analysis (Some Case Studies) - Effective ways to visualize - matplotlib, seaborn - ggplot2

Machine learning: Case Studies (Cont) - Natural language processing - Recommender system - Image classification

## Code

When you click the **Render** button a presentation will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```
